### ISSUE TITLE
accuracy and memory

### ISSUE THREAD

**Issue by cz-xjtu** [LIVIAETS/SizeLoss_WSS#1]
Hi, 
Thanks for your great works. I ran this code on PROMISE12 dataset and then tried to replace the dataset of my own, but found two questions:

1. when I ran your code and didn't change any parameters, but the results had some difference with  the results of paper(lower). I found the only thing maybe different is the division of  train and val sets, because it was divided randomly. I wander the seed you used to randomly divide the dataset.
2. I replace the dataset with mine using a val set containing more imgs, the GPU memory sharply increased when it comes to validation stage and cause "CUDA out of memory" error. I find the similar question's solution is to add "with torch.no_grad()", but it seems don't work for my error.

so, if you also met similar question or have some suggestions, would you please give me some help, thanks.

**Comment by HKervadec** [comment]
Hey,
Thanks for the interest in my work. About your two questions:

> when I ran your code and didn't change any parameters, but the results had some difference with the results of paper(lower). I found the only thing maybe different is the division of train and val sets, because it was divided randomly. I wander the seed you used to randomly divide the dataset.

Due to the network random initialization, and many un-deterministic parts in the software stack (CUDA and cudnn introduce a few of them I believe), results are never exactly the same. I did not had the resources (GPUs) at the time to train multiple time and average the results for each setting, so I had to report the value of only one run (I reran everything from scratch on another server once the code was fully debugged and stable). You might actually get higher or lower values when re-running it.

The dataset pre-processing and splitting is actually deterministic (at least as far as I found), as I seed the random generator https://github.com/LIVIAETS/SizeLoss_WSS/blob/master/slice_promise.py#L175. But to check quickly if we have the same split ; I end up with `1129/248` train/val slices before augmentation, and `5645/248` after. 

> I replace the dataset with mine using a val set containing more imgs, the GPU memory sharply increased when it comes to validation stage and cause "CUDA out of memory" error. I find the similar question's solution is to add "with torch.no_grad()", but it seems don't work for my error.

The dataloader I wrote does not resize the input images ; as I consider this should be done as pre-processing. What are the resolution of your images ?

**Comment by cz-xjtu** [comment]
Thanks for your patient answer.
For the first question, I had the same split as yours. And I also understand the uncertainty for training a deep net model. Thanks for your explanation. And I found you had two evaluation metrics "DSC" and "bDSC", which one did  you use in your paper or chose the higher one ?

And for the second question, I finally found the cause was that when it came to evaluation stage, the batch size became the numbers of slices in a volume and some of my volume contains too more slices which lead to a higher batch size.  So the  cuda is out of memory. I deactive the "groud" parameter https://github.com/LIVIAETS/SizeLoss_WSS/blob/0b10ce500524f28204689d2e32ce359b1115e3a0/main.py#L294, and solved the problem.

**Comment by HKervadec** [comment]
Ah, yes, the two issues are linked.

> And I found you had two evaluation metrics "DSC" and "bDSC", which one did you use in your paper or chose the higher one ?

It is true that this part is not clear. 
* DSC compute the average DSC on a slice basis (and average those individual DSCs). I usually refer to that one as 2D dice.
*  bDSC compute the DSC for the whole batch. When the whole batch contains all and only slices of a single patient, this effectively compute the DSC of the volume ; the 3D dice.

In the paper, I report the 3D dice (as we ultimately segment volumes) on all three datasets.

This way of computing it was working since those datasets did not had many slices (10/15 per patient approximately), but will (as you found out) cause memory errors when there is more slices. Two other methods to compute the 3D dice:
* Keep track of the intersection and pred/gt size on a patient basis in a dictionnary. You would reset it at the beginning of the epoch, and compute the ratio (2 * intersection / (pred + gt)) at the end.
* Save all the predictions and reconstruct the 3d volume later. Notice that the `metrics.py` script should be able to do that. It would use less GPU memory (no network, only 2d slices are loaded), and there is an option to do that on CPU if memory is still a limitation. The script might require some trivial debugging as I did not use that one often ; the dataloader functions might have evolved a tiny bit.
